package View;

import DAO.DAO_Escolas;
import DAO.DAO_ProfessoresAEE;
import Model.ProfessoresAEE;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author LucioMarlon
 */
public class FrmCadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastro_Professor
     */
    public FrmCadastroProfessor() {
        initComponents();
        AutoCompleteDecorator.decorate(cbAuxiliarDeSala);
        AutoCompleteDecorator.decorate(cbEscola);
        AutoCompleteDecorator.decorate(cbEstatus);
        AutoCompleteDecorator.decorate(cbTurnoProfessor);
        restauraComboEscola();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtProfessorRegular = new javax.swing.JTextField();
        txtProfessorAEE = new javax.swing.JTextField();
        brnCancelar = new javax.swing.JButton();
        cbAuxiliarDeSala = new javax.swing.JComboBox<>();
        cbEstatus = new javax.swing.JComboBox<>();
        cbTurnoProfessor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtEscolaVinculada = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbEscola = new javax.swing.JComboBox<>();
        txtDatacadastro = new javax.swing.JFormattedTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CREI - CADASTRO PROFESSOR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Professor AEE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Professor Regular");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Estatus");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Turno Professor");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Auxiliar de Sala");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Data Cadastro");

        btnCadastrar.setBackground(new java.awt.Color(204, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtProfessorRegular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtProfessorAEE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        brnCancelar.setBackground(new java.awt.Color(204, 255, 255));
        brnCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });

        cbAuxiliarDeSala.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbAuxiliarDeSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SIM", "NÃO", "PARCIAL" }));

        cbEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "A", "D" }));

        cbTurnoProfessor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTurnoProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "Integral", "Manhã", "Inter", "Tarde", "Manhã/Inter", "Tarde/Inter" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Escola Vinculada");

        txtEscolaVinculada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Escola");

        cbEscola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbEscola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));

        txtDatacadastro.setBackground(new java.awt.Color(204, 255, 255));
        try {
            txtDatacadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cbAuxiliarDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbTurnoProfessor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtProfessorAEE, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfessorRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtDatacadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addComponent(txtEscolaVinculada, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtProfessorAEE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEscolaVinculada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProfessorRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTurnoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(cbAuxiliarDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatacadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        this.dispose();    }//GEN-LAST:event_brnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    
//        String escolavinculada, professoregular;
            txtEscolaVinculada.getText();
            txtProfessorRegular.getText();
        
          
          String diaCadastro = txtDatacadastro.getText().substring(0, 2);
          String mesCadastro = txtDatacadastro.getText().substring(3, 5);
          String anoCadastro = txtDatacadastro.getText().substring(6);          
          
          String dataCadastro = anoCadastro+"-"+mesCadastro+"-"+diaCadastro;
        
        
        if (txtProfessorAEE.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Preencha no do PROFESSOR AEE");
        }       
     
        
        else if (cbAuxiliarDeSala.getSelectedItem().equals("SELECIONE"))
        {
            JOptionPane.showMessageDialog(null,"Preencha AUXILIAR DE SALA SIM/NÃO");
        }
        
        else if (cbTurnoProfessor.getSelectedItem().equals("SELECIONE"))
        {
            JOptionPane.showMessageDialog(null,"Em que turno o professor trabalha?");
        }
        
        else if (cbEstatus.getSelectedItem().equals("SELECIONE"))
        {
            JOptionPane.showMessageDialog(null,"Preencha o turno PROFESSOR");
        }
    
        
//        else if (txtDataCadastro.getText().isEmpty())
//        {
//            JOptionPane.showMessageDialog(null,"Data criação.");
//        }
        
          else if (dataCadastro.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Data da criação não pode ficar vazia.");
        }
        
        else if (cbEscola.getSelectedItem().equals("SELECIONE"))
        {
            JOptionPane.showMessageDialog(null,"SELECIONE A ESCOLA");
        }
        else
        {
            ProfessoresAEE objprofessores = new ProfessoresAEE(
                    txtProfessorAEE.getText().toUpperCase(),
                    txtEscolaVinculada.getText().toUpperCase(),
                    txtProfessorRegular.getText().toUpperCase(),
                    cbAuxiliarDeSala.getSelectedItem().toString(),
                    cbTurnoProfessor.getSelectedItem().toString(),
                    dataCadastro,
                    cbEstatus.getSelectedItem().toString(),
//                    txtDataCadastro.getText(),                                      
                    cbEscola.getSelectedIndex()           
            );
            
            DAO_ProfessoresAEE inserirProfessores = new DAO_ProfessoresAEE();            
            
            try
               {  
                   inserirProfessores.adicionar(objprofessores);                        
                   JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
                   txtProfessorAEE.setText("");
                   txtEscolaVinculada.setText("");
                   txtProfessorRegular.setText("");
                   cbAuxiliarDeSala.setSelectedItem("SELECIONE");
                   cbTurnoProfessor.setSelectedItem("SELECIONE");                   
                   txtDatacadastro.setText("");                  
                   cbEstatus.setSelectedItem("SELECIONE");
                   cbEscola.setSelectedItem("SELECIONE");                    
               }
               catch(HeadlessException erro)
               {
                   JOptionPane.showMessageDialog(null,"Ocorreu um erro ao "
                           + "cadastrar professor" + erro);
               } 
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    ArrayList<Integer> id_escola = new ArrayList<Integer>();
     public void restauraComboEscola()
    {
        try
        {
            DAO_Escolas objescolas = new DAO_Escolas();
            ResultSet resultadoSetado = objescolas.listarEscolas();
            
            while (resultadoSetado.next())
            {
                id_escola.add(resultadoSetado.getInt(1));                                                          
                cbEscola.addItem(resultadoSetado.getString(3));                                
            }
        }
        catch(SQLException erro)
         {
                    JOptionPane.showMessageDialog(null,"Erro ao carregar "
                            + "ComboBox ESCOLA" + erro);
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmCadastroProfessor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cbAuxiliarDeSala;
    private javax.swing.JComboBox<String> cbEscola;
    private javax.swing.JComboBox<String> cbEstatus;
    private javax.swing.JComboBox<String> cbTurnoProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtDatacadastro;
    private javax.swing.JTextField txtEscolaVinculada;
    private javax.swing.JTextField txtProfessorAEE;
    private javax.swing.JTextField txtProfessorRegular;
    // End of variables declaration//GEN-END:variables
}
